version: '3.8'
services:
  db:
    image: postgres
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: p-db
    networks:
      - inner

networks:
  inner:


      
      
